export const metadata = {
  title: "Privacy Policy | SoulsWed",
  description: "Privacy Policy of use for SoulsWed services.",
};

export default function PrivacyPage() {
  return (
    <main className="min-h-screen pt-32 pb-24 relative overflow-hidden">
      {/* Decorative Orbs */}
      <div className="absolute inset-0 pointer-events-none overflow-hidden">
        <div className="absolute top-[-10%] right-[-10%] w-[50%] h-[50%] bg-primary-400/5 blur-[120px] rounded-full" />
      </div>

      <div className="max-w-4xl mx-auto px-6 lg:px-8 relative z-10">
        <div className="mb-12">
          <h1 className="text-3xl md:text-5xl font-extrabold mb-4" style={{ color: "var(--sw-navy)", fontFamily: "var(--font-heading)" }}>
            Privacy Policy
          </h1>
          <p className="text-sm text-slate-500 font-medium">Last Updated: July 2026</p>
        </div>

        <div className="bg-white/80 backdrop-blur-xl rounded-[32px] p-8 md:p-12 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-white/60 text-sm md:text-base leading-relaxed">
          <section className="mb-10">
            <p className="mb-4 text-slate-600 leading-relaxed">
              Effective: June 2, 2024 This Privacy Policy describes the data protection practices of SoulsWed , (&quot;SW&quot;, &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). SW provides services to users throughout the world and is the data controller of your information. This Privacy Policy applies to the SoulsWed.com Web and mobile Web pages, the SoulsWed mobile app and associated SoulsWed branded websites and mobile applications owned and operated by us or our affiliates that link to this Privacy Policy (&quot;Affiliates&quot;), and related SoulsWed branded online and offline services thereto (the &quot;Services&quot;).
            </p>
          </section>
          <section className="mb-10">
            <h2 className="text-xl md:text-2xl font-bold mb-5" style={{ color: "var(--sw-navy)", fontFamily: "var(--font-heading)" }}>PLEASE READ THIS PRIVACY</h2>
            <p className="mb-4 text-slate-600 leading-relaxed">
              POLICY CAREFULLY TO UNDERSTAND HOW WE HANDLE YOUR INFORMATION. IF YOU DO NOT AGREE TO THIS PRIVACY POLICY, PLEASE DO NOT USE THE SERVICES. This Privacy Policy contains the following sections: 1. The Information We Collect and the Way We Use It 2. Cookies and Online Analytics 3. Online Advertising 4. How We Share and Disclose Your Information 5. Notice About Use of Our Forums and Features 6. Aggregate and De-Identified Information 7. Your Choices and Rights 8. Privacy Information
            </p>
            <p className="mb-4 text-slate-600 leading-relaxed">
              9. Third Party Links and Features 10. Children&apos;s Privacy 11. International Users 12. How We Protect Your Information 13. Retention of Your Information 14. Changes to Our Privacy Policy 15. SW Contact Information THE
            </p>
          </section>
          <section className="mb-10">
            <h2 className="text-xl md:text-2xl font-bold mb-5" style={{ color: "var(--sw-navy)", fontFamily: "var(--font-heading)" }}>INFORMATION WE COLLECT AND THE WAYS WE USE IT</h2>
            <p className="mb-4 text-slate-600 leading-relaxed">
              We obtain information about you through the means discussed below when you use our Services. The information we collect and the purposes for which we use it will depend to some extent on the specific Services you use and how you interact with SW. The following table describes the categories of information about you that we collect and how we collect and use such information. Categories of information collected Purposes of use Sources of personal information Contact and account registration information, e.g., name, email address, postal address, phone number, wireless device address, account username or screen name, and password Provide the Services Communicate with you Personalize your experience Secure our Services and users Fraud prevention and legal purposes You Other users who provide information about you in connection with their event or profile Consumer data resellers Public records databases Conferences and other events Our Affiliates
            </p>
            <p className="mb-4 text-slate-600 leading-relaxed">
              Demographic and statistical information, e.g., gender, interests, lifestyle information, and hobbies Communicate with you Provide the Services Personalize your experience You Other users who provide information about you in connection with their event or profile Consumer data resellers Our Affiliates Social media networks, in accordance with your privacy preferences on such services Financial and transactional information, e.g., shipping address, credit or debit card number, verification number, and expiration date, and information about your transactions and purchases with us Communicate with you Provide the Services Secure our Services and users Fraud prevention and legal purposes You Third-party payment processors who collect this information on our behalf and who also have an independent relationship with you Third party suppliers and sellers User-generated content, e.g., photos, videos, audio, information about your events, any information you submit in public SW forums or message boards, reviews you leave for vendors, and feedback or testimonials you provide about our Services Provide the Services Communicate with you Personalize your experience Secure our Services and users You Other users who provide information about you in connection with their event or profile
            </p>
            <p className="mb-4 text-slate-600 leading-relaxed">
              Customer service information, e.g., questions and other messages you address to us directly through online forms, by email, over the phone, or by post; and summaries or voice recordings of your interactions with customer care Communicate with you Provide the Services Secure our Services and users Fraud prevention and legal purposes You Other Affiliates Communications with event vendors and partners, e.g., your in-Services messages and calls to vendors and advertising partners, and information surrounding those messages such as the date/time of the communication, the originating number, the recipient number, the duration of a call, and your location as determined by your area code Provide the Services Secure our Services and users Fraud prevention and legal purposes You The event vendors with which you communicate Communicate with you Provide the Services
            </p>
            <p className="mb-4 text-slate-600 leading-relaxed">
              Research, survey, or sweepstakes information, e.g., if you participate in a survey or sweepstakes, we collect information needed for you to participate (such as contact information), and to fulfill your prize Communicate with you Provide the Services Secure our Services and users Fraud prevention and legal purposes You Survey or sweepstakes partners Researchers and analysts Information about others, e.g., if you use a &quot;tell-a-friend&quot; tool (or similar feature) that allows you to send information to another person, or invite them to participate in an event, web site, registry or other property, or include their information within our products as part of your wedding planning experience (for example so they may receive save the date and RSVP notifications and wedding invitations) we will collect, at a minimum, the recipient&apos;s email address; or, if you provide us with information about other people involved in your events (such as your fiance, partner, or guests). In providing this information, you represent that you are authorized to provide it. Provide the Services Personalize your experience Fraud prevention and legal purposes You Other users (if you are the recipient of a communication) Our Affiliates Device information and identifiers, e.g., IP address; browser type and language; operating system; platform type; device type; software and hardware attributes; and unique device, advertising, and app identifiers Provide the Services Personalize your experience Secure our Services and users Fraud prevention and legal purposes You Advertising providers Analytics providers Cookies and tracking technologies Provide the Services
            </p>
            <p className="mb-4 text-slate-600 leading-relaxed">
              Connection and usage data, e.g., information about files you download, domain names, landing pages, browsing activity, content or ads viewed and clicked, dates and times of access, pages viewed, forms you complete or partially complete, search terms, uploads or downloads, whether you open an email and your interaction with email content, access times, error logs, and other similar information Provide the Services Personalize your experience Secure our Services and users Fraud prevention and legal purposes You Advertising providers Analytics providers Cookies and tracking technologies Marketers Our Affiliates Geolocation, e.g., city, state, country, and ZIP code associated with your IP address or derived through Wi-Fi triangulation; and, with your permission in accordance with your mobile device settings, and precise geolocation information from GPS-based functionality on your mobile devices Provide the Services Personalize your experience Secure our Services and users Fraud prevention and legal purposes You Advertising providers Analytics providers Marketers Our Affiliates Social media information, e.g., if you access the Services through a third-party connection or log-in, we may have access to information you provide to that social network such as your name, email address, friend list, photo, gender, location, and current city; and information you provide to us directly through our pages on social networking and blogging platforms (e.g., Facebook, Instagram, Snapchat, Wordpress, and Twitter) Provide the Services Communicate with you Personalize your experience Secure our Services and users You Social media networks, in accordance with your privacy preferences on such services
            </p>
            <p className="mb-4 text-slate-600 leading-relaxed">
              Other information, e.g., any other information you choose to directly provide to SW in connection with your use of the Services Provide the Services Communicate with you Personalize your experience Secure our Services and users Fraud prevention and legal purposes You The following chart provides additional information about the purposes and legal bases for collecting and using your information Purposes of Use Legal Basis Communicate with you, for example: Responding to your requests for information and provide you with more effective and efficient customer service and technical support Providing you with transactional updates and information about the Services (e.g., inform you about updates to our Services, information about your account, or information about ecommerce transactions that you conduct on the Services) In accordance with applicable legal requirements, contacting you by email, postal mail, phone, or SMS regarding SW, our Affiliates, and third-party products, services, surveys, promotions, special events and other subjects that we think may be of interest to you Our Legitimate Business Interests With Your Consent
            </p>
            <p className="mb-4 text-slate-600 leading-relaxed">
              Provide the Services, for example: Processing and fulfilling your transactions Assisting you in submitting or requesting a vendor quote Providing community features and posting your content, including any testimonials you provide Engaging in analysis, research, and reports to better understand how you use the Services, so we can improve them Administering entries into sweepstakes, contests, promotions, or surveys Sending communications that you have requested on your behalf, such as if you request to connect your profile with a family member or friend or send a tell-a-friend or vendor message Understanding and resolving app crashes and other issues being reported Performance of a contract - to provide the Services to you Our Legitimate Business Interests Personalize your experience, for example: Customizing the advertising and content on the Services based on your activities and interests Creating and updating audience segments that can be used for targeted advertising and marketing on the Services, third party services and platforms, and mobile apps Creating profiles about you, including adding and combining information we obtain from third parties, which may be used for analytics, marketing, and advertising Sending you personalized newsletters, surveys, and information about products, services and promotions offered by us, our partners, and other organizations with which we work Our Legitimate Business Interests With Your Consent Secure our Services and users, for example: Monitoring, preventing, and detecting fraud, such as through verifying your identity Combatting spam or other malware or security risks Monitoring, enforcing, and improving the security of our Services Our Legitimate Business Interests To Comply with Legal Obligations and Protect Our Legal Rights
            </p>
            <p className="mb-4 text-slate-600 leading-relaxed">
              Fraud detection and prevention, defending our legal rights and compliance with the law, for example: Complying with any applicable procedures, laws, and regulations where it is necessary for our legitimate interests or the legitimate interests of others Establishing, exercising, or defending our legal rights where it is necessary for our legitimate interests or the legitimate interests of others (e.g., to enforce compliance with our Terms of Use, Privacy Policies, or to protect our Services, users, or others) Our Legitimate Business Interests To Comply with Legal Obligations and Protect Our Legal Rights Combined Information. For the purposes discussed in this Privacy Policy, we may combine the information that we collect through the Services with information that we receive from other sources, both online and offline, and use such combined information in accordance with this Privacy Policy.
            </p>
          </section>
          <section className="mb-10">
            <h2 className="text-xl md:text-2xl font-bold mb-5" style={{ color: "var(--sw-navy)", fontFamily: "var(--font-heading)" }}>B. COOKIES AND ONLINE</h2>
            <p className="mb-4 text-slate-600 leading-relaxed">
              ANALYTICS We use a variety of online tracking and analytics tools (e.g., cookies, flash cookies, pixel tags, and HTML5) to collect and analyze information as you use the Services. Among other things, these technologies allow us to offer you a more tailored experience in the future, by understanding and remembering your particular browsing and usage preferences. We may also use third-party web analytics services (such as those of Google Analytics, Coremetrics, Mixpanel, and Segment) on our Services to collect and analyze information collected through these technologies to assist us in auditing, research, or reporting; fraud prevention; and providing certain features to you. The types of tracking and analytics tools we and our service providers use for these purposes are: &quot;Cookies&quot; are small data files stored on your computer or device to collect information about your use of the Services. Cookies may enable us to recognize you as the same user who used our Services in the past, and relate your use of the Services to other information we have about you. Cookies may also be used to enhance your experience on the Services (for example, by storing your username) and/or to collect general usage and aggregated statistical information. Most browsers can be set to detect cookies and give you an opportunity to reject them, but refusing cookies may, in some cases, limit your use of our Services or features. Please note that by blocking, disabling, or managing any or all cookies, you may not have access to certain features or offerings of the Services. &quot;Local shared objects,&quot; or &quot;flash cookies,&quot; may be stored on your computer or device using a media player or other software. Local shared objects operate much like cookies, but cannot be managed in the same way. Depending on how local shared objects are enabled on your computer or device, you may be able to manage them using software settings.
            </p>
            <p className="mb-4 text-slate-600 leading-relaxed">
              A &quot;pixel tag&quot; (also known as a &quot;clear GIF&quot; or &quot;web beacon&quot;) is a tiny image - typically just one-pixel - that can be placed on a web page or in our electronic communications to you in order to help us measure the effectiveness of our content by, for example, counting the number of individuals who visit us online or verifying whether you&apos;ve opened one of our emails or seen one of our web pages. &quot;HTML5&quot; (the language some websites, such as mobile websites, are coded in) may be used to store information on your computer or device about your usage of the Services so that we may improve and customize them for you.
            </p>
          </section>
          <section className="mb-10">
            <h2 className="text-xl md:text-2xl font-bold mb-5" style={{ color: "var(--sw-navy)", fontFamily: "var(--font-heading)" }}>C. ONLINE ADVERTISING</h2>
            <h3 className="text-lg md:text-xl font-bold mb-3 mt-8 text-slate-800">1. Online Advertising Overview</h3>
            <p className="mb-4 text-slate-600 leading-relaxed">
              The Services may integrate third-party advertising technologies that allow for the delivery of relevant content and advertising on the Services, as well as on other websites you visit and other applications you use. The ads may be based on various factors such as the content of the page you are visiting, your searches, demographic data, user-generated content, and other information we collect from you. These ads may be based on your current activity or your activity over time and across other websites and online services and may be tailored to your interests. Third parties, whose products or services are accessible or advertised via the Services, may also place cookies or other tracking technologies on your computer, mobile phone, or other device to collect information about you as discussed above. We also allow other third parties (e.g., ad networks and ad servers such as Google and others) to serve tailored ads to you on the Services, other sites, and in other applications, and to access their own cookies or other tracking technologies on your computer, mobile phone, or other device you use to access the Services. We sometimes provide our customer information (such as email addresses) to service providers, who may &quot;match&quot; this information in de-identified form to cookies (or mobile ad identifiers) and other proprietary IDs, in order to provide you with more relevant ads when you visit other websites and mobile applications. We neither have access to, nor does this Privacy Policy govern, the use of cookies or other tracking technologies that may be placed on your device you use to access the Services by such non-affiliated third parties. To opt out of Google Analytics for display advertising or customize Google display network ads, visit the Google Ads Settings page (https://adssettings.google.com/authenticated) . We do not control these opt-out links or whether any particular company chooses to participate in these opt-out programs. We are not responsible for any choices you make using these mechanisms or the continued availability or accuracy of these mechanisms. Please note that if you exercise the opt out choices above, you will still see advertising when you use the Services, but it will not be tailored to you based on your online behavior over time.
            </p>
            <h3 className="text-lg md:text-xl font-bold mb-3 mt-8 text-slate-800">2. Mobile Advertising</h3>
            <p className="mb-4 text-slate-600 leading-relaxed">
              When using mobile applications from SW or others, you may also receive tailored in-application advertisements. We may use third-party service providers to deliver advertisements on mobile applications or for mobile application analytics. Each operating system, iOS for Apple phones, Android for Android devices, and Windows for Microsoft devices provides its own instructions on how to prevent the delivery of tailored in-application advertisements. We do not control how the applicable platform operator allows you to control receiving personalized in-application advertisements; thus, you should contact the platform provider for further details on opting out of tailored in-application advertisements. You may review the support materials and/or the device settings for the respective operating systems to opt-out of tailored in-app advertisements.
            </p>
            <h3 className="text-lg md:text-xl font-bold mb-3 mt-8 text-slate-800">3. Notice Concerning Do Not Track.</h3>
            <p className="mb-4 text-slate-600 leading-relaxed">
              Do Not Track (&quot;DNT&quot;) is a privacy preference that users can set in certain web browsers. We are committed to providing you with meaningful choices about the information collected on our website for online advertising and analytics purposes, and that is why we provide the variety of opt-out mechanisms listed above. However, we do not currently recognize or respond to browser-initiated DNT signals. Learn more about Do Not Track (https://allaboutdnt.com/) .
            </p>
          </section>
          <section className="mb-10">
            <h2 className="text-xl md:text-2xl font-bold mb-5" style={{ color: "var(--sw-navy)", fontFamily: "var(--font-heading)" }}>D. HOW WE SHARE AND</h2>
          </section>
          <section className="mb-10">
            <h2 className="text-xl md:text-2xl font-bold mb-5" style={{ color: "var(--sw-navy)", fontFamily: "var(--font-heading)" }}>DISCLOSE YOUR INFORMATION</h2>
            <p className="mb-4 text-slate-600 leading-relaxed">
              SW will share the information collected from and about you as discussed above for various business purposes. The chart below explains the categories of third parties with which we may share your information, and the categories of information we may share with each. Third Parties with which we share information and why Categories of information shared Our Affiliates. We may share information we collect within the SW family of companies to deliver products and services to you, ensure a consistent level of service across our products and Services, and enhance our products, services, and your customer experience All categories of information we collect may be shared with our Affiliates Service Providers that Perform Services on our Behalf. We may share information with service providers, including billing and payment processing, sales, marketing, advertising, data analysis and insight, research, technical support and customer service, shipping and fulfillment, data storage, security, fraud prevention, and legal services providers. All categories of information we collect may be shared with our service providers Other Individuals, Services, and Vendors at Your Request. We will share your information with other individuals and services at your request. For example, if you communicate with a vendor you connect with through the Services, we may share information, as well as the contents of your message, so that the vendor may contact you pursuant to such vendor&apos;s privacy policy and applicable legal agreements. Moreover, if you participate in one of our registry programs, we will share your information with your friends, families, and other contacts as well as the registry program participants. Geolocation Other Information
            </p>
            <p className="mb-4 text-slate-600 leading-relaxed">
              Third Party Partners for Marketing Purposes. We may share your information with partners whose offerings we think may interest you. For example, if you participate in a registry program, or register for certain of our Services, we may share information with our Affiliates and other third parties (organizations that have offerings we think may interest you, registry program participants, retailers, other program participants, or other third-parties) for their marketing and other purpose Contact and account registration Demographic and statistical information Geolocation Other Information Third Party Partners to Provide Co-Branded Products and Services. In some cases, we may share information with third-party partners to provide co-branded products or services, including contests, sweepstakes, and joint activities. For example, if you choose to interact with such co-branded products or services using your account information with us, we may share your account information with third parties as required to provide the co-branded product or service that you request, including any information required for contest prize fulfillment. Contact and account registration Demographic and statistical information Financial and transactional information User-generated content Research, survey, or sweepstakes information Geolocation Other Information Third Parties for Legal Purposes. By using the Services, you acknowledge and agree that we may access, retain, and disclose the information we collect and maintain about you if required to do so by law or in a good faith belief that such access, retention or disclosure is reasonably necessary to: (a) comply with legal process or a regulatory investigation (e.g. a subpoena or court order); (b) enforce our Terms of Service, this Privacy Policy, or other contracts with you, including investigation of potential violations thereof; (c) respond to claims that any content violates the rights of third parties; and/or (d) protect the rights, property or personal safety of SW, its agents and Affiliates, its users and/or the public. This includes exchanging information with other companies and organizations for fraud protection, and spam/malware prevention, and similar purposes. All categories of information we collect may be shared for legal purposes
            </p>
            <p className="mb-4 text-slate-600 leading-relaxed">
              Third Parties in a Business Transaction. We may disclose or transfer information in connection with a corporate transaction, including for example a merger, investment, acquisition, reorganization, consolidation, bankruptcy, liquidation, or sale of some or all of our assets. All categories of information we collect may be shared in connection with a business transaction Third-Party Online Advertisers and Ad Networks. As discussed in the &quot;Online Advertising&quot; Section above, the Services may integrate third-party advertising technologies that allow for the delivery of relevant content and advertising on the Services, as well as on other websites you visit and other applications you use, and these technologies will collect certain information from your use of the Services to assist in delivering such ads. Demographic and statistical information User-generated content Device information and identifiers Connection and usage data Geolocation Social media information
            </p>
          </section>
          <section className="mb-10">
            <h2 className="text-xl md:text-2xl font-bold mb-5" style={{ color: "var(--sw-navy)", fontFamily: "var(--font-heading)" }}>E. NOTICE ABOUT USE OF</h2>
          </section>
          <section className="mb-10">
            <h2 className="text-xl md:text-2xl font-bold mb-5" style={{ color: "var(--sw-navy)", fontFamily: "var(--font-heading)" }}>OUR FORUMS AND FEATURES</h2>
            <p className="mb-4 text-slate-600 leading-relaxed">
              Certain features of our Services make it possible for you to share comments publicly and privately with other users, such as through our public forums, chat rooms, blogs, personal messages, review features, and message boards. You should be aware that any information you provide or post in these ways may be read, collected, and used by others who access them. While we do not have an obligation to monitor the content of messages sent using our Services, we reserve the right to, in our discretion. We encourage you to be cautious about the information you submit (e.g., choose a username that does not disclose your personal identity). Whenever you post something in our Services, social media and any other third party platforms we control, it may be impossible to remove all instances of the posted information, for example, if someone has taken a screenshot of your posting. You may be required to register with a third-party application to post a comment. Moreover, please note that if you participate in one of our registry programs, in some instances, you can choose to make your registries available only to guests and friends via a password. If you do not elect this option, then any user will be able to search for and view your registry by using your first and/or last name and other information regarding your event.
            </p>
          </section>
          <section className="mb-10">
            <h2 className="text-xl md:text-2xl font-bold mb-5" style={{ color: "var(--sw-navy)", fontFamily: "var(--font-heading)" }}>F. AGGREGATE AND</h2>
            <p className="mb-4 text-slate-600 leading-relaxed">
              DE-IDENTIFIED INFORMATION We may aggregate and/or de-identify any information collected through the Services so that such information can no longer be linked to you or your device (&quot;Aggregate/De-Identified Information&quot;). We may use Aggregate/De-Identified Information for any purpose, including without limitation for research and marketing purposes, and may also share such data with any third parties, including advertisers, promotional partners, and sponsors, in our discretion.
            </p>
          </section>
          <section className="mb-10">
            <h2 className="text-xl md:text-2xl font-bold mb-5" style={{ color: "var(--sw-navy)", fontFamily: "var(--font-heading)" }}>G. YOUR CHOICES AND</h2>
            <p className="mb-4 text-slate-600 leading-relaxed">
              RIGHTS You have certain rights with respect to your information as further described in this Section, in addition to any rights discussed elsewhere in this Privacy Policy. Marketing Communications. You may instruct us not to use your information to contact you by email, postal mail, or phone regarding products, services, promotions and special events that might appeal to your interests by contacting us using the information below. In commercial email messages, you can also opt out by following the instructions located at the bottom of such emails. Please note that, regardless of your request, we may still use and share certain information as permitted by this Privacy Policy or as required by applicable law. For example, you may not opt out of certain operational emails, such as those reflecting our relationship or transactions with you. Consumer Privacy Rights. Depending on the laws of your local jurisdiction, you may have certain rights and choices with respect to your information. For example, under local laws, you may be able to ask us to: Provide access to certain information we hold about you Update or correct your information Delete certain information Restrict the use of your information We will consider all requests and provide our response within the time period stated by applicable law. Please note, however, that certain information may be exempt from such requests in some circumstances, which may include if we need to keep processing your information for our legitimate interests or to comply with a legal obligation. We will let you know where this is the case or if certain rights don&apos;t apply in your country or state of residence. We may request you provide us with information necessary to verify your identity before responding to your request as required or permitted by applicable law. Testimonials/Notable Quotes. On some of our Services, and with your consent, we post notable quotes or testimonials which may contain information such as your name, event type, city, state, and quote or testimonial. Requests for removal of a user testimonial can be done by contacting us as detailed in the &quot;SW Contact Information&quot; section below.
            </p>
          </section>
          <section className="mb-10">
            <h2 className="text-xl md:text-2xl font-bold mb-5" style={{ color: "var(--sw-navy)", fontFamily: "var(--font-heading)" }}>H. THIRD PARTY LINKS AND</h2>
            <p className="mb-4 text-slate-600 leading-relaxed">
              FEATURES The Services may contain links, banners, widgets or advertisements (e.g., a &quot;Share It!&quot; or &quot;Like&quot; button) that lead to other websites, apps, or services not subject to this Privacy Policy (including other sites that may be co-branded with our brands). On some of our Services, you may also be able to register with or purchase directly from third-party retailers. We are not responsible for the privacy practices or the content of any other websites to which the Services link or which link to our Services. The privacy policies of these other sites will govern the collection and use of your information thereon, and we encourage you to read each such policy to learn about how your information may be treated by others.
            </p>
          </section>
          <section className="mb-10">
            <h2 className="text-xl md:text-2xl font-bold mb-5" style={{ color: "var(--sw-navy)", fontFamily: "var(--font-heading)" }}>I. CHILDREN&apos;S PRIVACY</h2>
            <p className="mb-4 text-slate-600 leading-relaxed">
              The Services are intended for general audiences and not for children under the age of 13. If we become aware that we have collected &quot;personal information&quot; (as defined by the United States Children&apos;s Online Privacy Protection Act) from children under the age of 13 without legally-valid parental consent, we will take reasonable steps to delete it as soon as possible. We do not knowingly process data of EU residents under the age of 16 without parental consent. If we become aware that we have collected data from an EU resident under the age of 16 without parental consent, we will take reasonable steps to delete it as soon as possible. We also comply with other age restrictions and requirements in accordance with applicable local laws.
            </p>
          </section>
          <section className="mb-10">
            <h2 className="text-xl md:text-2xl font-bold mb-5" style={{ color: "var(--sw-navy)", fontFamily: "var(--font-heading)" }}>J. INTERNATIONAL USERS</h2>
            <p className="mb-4 text-slate-600 leading-relaxed">
              Our Services are targeted to individuals across the globe. SW may subcontract the processing of your data to, or otherwise share your data within the SW family of companies, trusted service providers, and trusted business partners located in countries other than your country of residence, in accordance with applicable law. Such third parties may be engaged in, among other things, the provision of Services to you, the processing of transactions and/or the provision of support services. By providing us with your information, you acknowledge any such transfer, storage or use. For more information about these transfer mechanisms, please contact us as detailed in the &quot;SW Contact Information&quot; section below.
            </p>
          </section>
          <section className="mb-10">
            <h2 className="text-xl md:text-2xl font-bold mb-5" style={{ color: "var(--sw-navy)", fontFamily: "var(--font-heading)" }}>K. HOW WE PROTECT YOUR</h2>
          </section>
          <section className="mb-10">
            <h2 className="text-xl md:text-2xl font-bold mb-5" style={{ color: "var(--sw-navy)", fontFamily: "var(--font-heading)" }}>INFORMATION</h2>
            <p className="mb-4 text-slate-600 leading-relaxed">
              We take a variety of physical, technical, administrative, and organizational security measures to protect your information against accidental or unlawful destruction or accidental loss, alteration, unauthorized disclosure or access. However, no method of transmission over the Internet, and no means of electronic or physical storage, is absolutely secure. As such, you acknowledge and accept that we cannot guarantee the security of your information transmitted to, through, or on our Services or via the Internet and that any such transmission is at your own risk.
            </p>
            <p className="mb-4 text-slate-600 leading-relaxed">
              When you sign up for an account, you may be required to establish a username and password. If you create an account with us, you are responsible for maintaining the confidentiality of your account password and for any activity that occurs under your account. We are not responsible for any loss or damage arising from your failure to maintain the confidentiality of your password. If you use messaging or call features that allow you to interact with events vendors and others directly through our Services, please note that for security purposes, you should not include any passwords, social security numbers, payment card information, or other sensitive information in such communications.
            </p>
          </section>
          <section className="mb-10">
            <h2 className="text-xl md:text-2xl font-bold mb-5" style={{ color: "var(--sw-navy)", fontFamily: "var(--font-heading)" }}>L. RETENTION OF YOUR</h2>
          </section>
          <section className="mb-10">
            <h2 className="text-xl md:text-2xl font-bold mb-5" style={{ color: "var(--sw-navy)", fontFamily: "var(--font-heading)" }}>INFORMATION</h2>
            <p className="mb-4 text-slate-600 leading-relaxed">
              We store and maintain your information for the purposes for which it is processed by us. The length of time for which we retain information depends on the purposes for which we collected and use it and/or as required to comply with applicable laws.
            </p>
          </section>
          <section className="mb-10">
            <h2 className="text-xl md:text-2xl font-bold mb-5" style={{ color: "var(--sw-navy)", fontFamily: "var(--font-heading)" }}>M. CHANGES TO OUR PRIVACY</h2>
            <p className="mb-4 text-slate-600 leading-relaxed">
              POLICY We reserve the right to amend this Privacy Policy to reflect changes in the law, our data collection and use practices, the features of our Services, or advances in technology. We will make the revised Privacy Policy accessible through the Services, so you should review the Policy periodically. You can know if the Privacy Policy has changed since the last time you reviewed it by checking the &quot;Effective Date&quot; included at the beginning of the document. If we make a material change to the Policy, you will be provided with appropriate notice in accordance with legal requirements. By continuing to use the Services, you are confirming that you have read and understood the latest version of this Privacy Policy.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
