import { connectDB } from "../lib/mongodb";
import { Vendor } from "../lib/models/Vendor";

// Note: Using exact slug matching from config (venues, rooms, planners, caterers, decorators)

const vendors = [
  // 1. Venues
  {
    name: "The Ritz-Carlton New York, NoMad",
    businessName: "The Ritz-Carlton New York",
    email: "events@ritzcarltonnomad.com",
    city: "New York, United States",
    category: "venues", // Legacy field
    categories: ["venues"], // New array field
    priceFrom: 144000,
    rating: 5,
    reviewCount: 142,
    description: "Experience the ultimate luxury wedding venue at The Ritz-Carlton New York, NoMad. Featuring breathtaking views of the city skyline and world-class service.",
    featured: true,
    verified: true,
  },
  {
    name: "Conrad New York Downtown",
    businessName: "Conrad New York",
    email: "weddings@conradny.com",
    city: "New York, United States",
    category: "venues",
    categories: ["venues"],
    priceFrom: 50000,
    rating: 5,
    reviewCount: 98,
    description: "An extraordinary all-suite luxury hotel offering a sophisticated setting for your special day in lower Manhattan.",
    featured: false,
    verified: true,
  },
  {
    name: "Refinery Hotel New York",
    businessName: "Refinery Hotel",
    email: "events@refineryhotel.com",
    city: "New York, United States",
    category: "venues",
    categories: ["venues"],
    priceFrom: 38000,
    rating: 4.8,
    reviewCount: 65,
    description: "A luxury boutique hotel in the Garment District. The perfect blend of historic charm and modern elegance for your wedding.",
    featured: false,
    verified: true,
  },
  {
    name: "JW Marriott Hotel Hong Kong",
    businessName: "JW Marriott HK",
    email: "weddings@marriotthk.com",
    city: "Hong Kong",
    category: "venues",
    categories: ["venues"],
    priceFrom: 27000,
    rating: 4.9,
    reviewCount: 210,
    description: "Celebrate your romance at JW Marriott Hotel Hong Kong. Let our expert planners design a flawless event in our pillar-less ballroom.",
    featured: true,
    verified: true,
  },
  {
    name: "InterContinental Grand Stanford",
    businessName: "InterContinental HK",
    email: "events@grandstanford.com",
    city: "Hong Kong",
    category: "venues",
    categories: ["venues"],
    priceFrom: 17000,
    rating: 4.7,
    reviewCount: 112,
    description: "Stunning Victoria Harbour views and award-winning dining make this the perfect venue for a memorable wedding.",
    featured: false,
    verified: true,
  },

  // 2. Rooms (Extrapolated premium rooms/suites for guests)
  {
    name: "The Plaza Hotel - Royal Suite",
    businessName: "The Plaza",
    email: "reservations@theplaza.com",
    city: "New York, United States",
    category: "rooms",
    categories: ["rooms"],
    priceFrom: 120000,
    rating: 5,
    reviewCount: 340,
    description: "The ultimate luxury accommodation for the bride and groom. Exquisite decor, unparalleled service, and iconic Central Park views.",
    featured: true,
    verified: true,
  },
  {
    name: "Burj Al Arab - Panoramic Suite",
    businessName: "Jumeirah Hotels",
    email: "stay@burjalarab.com",
    city: "Dubai, UAE",
    category: "rooms",
    categories: ["rooms"],
    priceFrom: 95000,
    rating: 5,
    reviewCount: 412,
    description: "A spectacular two-story suite with floor-to-ceiling windows offering uninterrupted views of the Arabian Gulf.",
    featured: true,
    verified: true,
  },
  {
    name: "Four Seasons - Ocean View Villa",
    businessName: "Four Seasons Bora Bora",
    email: "resort@fourseasonsbb.com",
    city: "Bora Bora, French Polynesia",
    category: "rooms",
    categories: ["rooms"],
    priceFrom: 85000,
    rating: 4.9,
    reviewCount: 189,
    description: "Overwater bungalows and beachfront villa estates offering the most romantic setting for your destination wedding or honeymoon.",
    featured: false,
    verified: true,
  },
  {
    name: "The Savoy - Thames Foyer Suite",
    businessName: "The Savoy",
    email: "booking@thesavoylondon.com",
    city: "London, UK",
    category: "rooms",
    categories: ["rooms"],
    priceFrom: 65000,
    rating: 4.8,
    reviewCount: 201,
    description: "Experience Edwardian elegance and Art Deco style in the heart of London. Perfect for hosting your distinguished wedding guests.",
    featured: false,
    verified: true,
  },
  {
    name: "Taj Lake Palace - Grand Royal Suite",
    businessName: "Taj Hotels",
    email: "reservations@tajhotels.com",
    city: "Udaipur, India",
    category: "rooms",
    categories: ["rooms"],
    priceFrom: 45000,
    rating: 4.9,
    reviewCount: 256,
    description: "Live like royalty in a marble palace floating on Lake Pichola. A magical, unforgettable accommodation experience.",
    featured: false,
    verified: true,
  },

  // 3. Wedding Planners
  {
    name: "Eve Experience",
    businessName: "Eve Experience Event Management",
    email: "hello@eveexperience.com",
    city: "Kollam, India",
    category: "planners",
    categories: ["planners"],
    priceFrom: 260000,
    rating: 4.9,
    reviewCount: 45,
    description: "Enjoy your special day while the experts take care of the details. End-to-end event management for luxury weddings.",
    featured: true,
    verified: true,
  },
  {
    name: "SANS Events",
    businessName: "SANS Event Organizers",
    email: "contact@sansevents.com",
    city: "Kochi, India",
    category: "planners",
    categories: ["planners"],
    priceFrom: 250000,
    rating: 4.8,
    reviewCount: 38,
    description: "Bringing your vision to life with meticulous planning, stunning designs, and flawless execution.",
    featured: true,
    verified: true,
  },
  {
    name: "Vows & Veils Planning",
    businessName: "Vows & Veils",
    email: "info@vowsandveils.com",
    city: "London, UK",
    category: "planners",
    categories: ["planners"],
    priceFrom: 350000,
    rating: 5,
    reviewCount: 120,
    description: "Award-winning international wedding planners specializing in destination weddings across Europe and beyond.",
    featured: false,
    verified: true,
  },
  {
    name: "The Wedding Design Company",
    businessName: "WDC",
    email: "plan@wdc.com",
    city: "New Delhi, India",
    category: "planners",
    categories: ["planners"],
    priceFrom: 400000,
    rating: 4.9,
    reviewCount: 88,
    description: "Curating bespoke luxury weddings. We handle everything from venue selection to entertainment, ensuring a seamless celebration.",
    featured: false,
    verified: true,
  },
  {
    name: "Luxe Events Co.",
    businessName: "Luxe Events",
    email: "hello@luxeevents.com",
    city: "Dubai, UAE",
    category: "planners",
    categories: ["planners"],
    priceFrom: 450000,
    rating: 4.7,
    reviewCount: 52,
    description: "Creating unforgettable, high-profile events. Our dedicated team guarantees a stress-free and spectacular wedding day.",
    featured: false,
    verified: true,
  },

  // 4. Caterers (Extrapolated premium caterers)
  {
    name: "Gastronomic Excellence",
    businessName: "Gastronomic Excellence Catering",
    email: "events@gastroexcellence.com",
    city: "Paris, France",
    category: "caterers",
    categories: ["caterers"],
    priceFrom: 18000, // Price per plate roughly
    rating: 5,
    reviewCount: 130,
    description: "Michelin-starred culinary experiences brought to your wedding venue. Exquisite French cuisine with impeccable presentation.",
    featured: true,
    verified: true,
  },
  {
    name: "The Royal Feast",
    businessName: "Royal Feast Catering",
    email: "book@royalfeast.in",
    city: "Jaipur, India",
    category: "caterers",
    categories: ["caterers"],
    priceFrom: 5500,
    rating: 4.8,
    reviewCount: 240,
    description: "Authentic, rich, and lavish Indian feasts cooked by master chefs. Serving traditional delicacies that your guests will talk about for years.",
    featured: true,
    verified: true,
  },
  {
    name: "Global Palate Events",
    businessName: "Global Palate",
    email: "tastings@globalpalate.com",
    city: "New York, United States",
    category: "caterers",
    categories: ["caterers"],
    priceFrom: 12500,
    rating: 4.9,
    reviewCount: 95,
    description: "Customized menus featuring global cuisines, crafted with locally sourced organic ingredients for the modern, conscious couple.",
    featured: false,
    verified: true,
  },
  {
    name: "La Dolce Vita Catering",
    businessName: "La Dolce Vita",
    email: "ciao@ladolcevitacatering.it",
    city: "Rome, Italy",
    category: "caterers",
    categories: ["caterers"],
    priceFrom: 14000,
    rating: 4.7,
    reviewCount: 110,
    description: "Bringing the authentic taste of Italy to your celebration. From wood-fired pizzas to elegant multi-course Tuscan dinners.",
    featured: false,
    verified: true,
  },
  {
    name: "Oceanic Bites & Bar",
    businessName: "Oceanic Catering",
    email: "hello@oceanicbites.com",
    city: "Sydney, Australia",
    category: "caterers",
    categories: ["caterers"],
    priceFrom: 9500,
    rating: 4.6,
    reviewCount: 78,
    description: "Premium seafood and modern Australian cuisine, complete with a team of expert mixologists for your wedding bar.",
    featured: false,
    verified: true,
  },

  // 5. Decorators
  {
    name: "Beretania Florist",
    businessName: "Beretania Floral Design",
    email: "weddings@beretaniaflorist.com",
    city: "Honolulu, United States",
    category: "decorators",
    categories: ["decorators"],
    priceFrom: 29223,
    rating: 4.9,
    reviewCount: 67,
    description: "Let's bring your vision to life. Stunning tropical floral arrangements and event design for your Hawaiian wedding.",
    featured: true,
    verified: true,
  },
  {
    name: "French Florist",
    businessName: "French Florist Events",
    email: "design@frenchflorist.com",
    city: "California, United States",
    category: "decorators",
    categories: ["decorators"],
    priceFrom: 25048,
    rating: 4.8,
    reviewCount: 115,
    description: "Transforming spaces with elegance. Specializing in romantic, lush, and grand floral installations.",
    featured: true,
    verified: true,
  },
  {
    name: "Les Filles d'a cote",
    businessName: "Les Filles Decor",
    email: "bonjour@lesfilles.fr",
    city: "Paris, France",
    category: "decorators",
    categories: ["decorators"],
    priceFrom: 12656,
    rating: 4.7,
    reviewCount: 42,
    description: "Chic and sophisticated Parisian event styling. We create breathtaking atmospheres for intimate celebrations.",
    featured: false,
    verified: true,
  },
  {
    name: "Royal Petals Decor",
    businessName: "Royal Petals",
    email: "info@royalpetals.in",
    city: "Mumbai, India",
    category: "decorators",
    categories: ["decorators"],
    priceFrom: 85000,
    rating: 4.9,
    reviewCount: 180,
    description: "Extravagant mandaps, majestic stage setups, and immersive lighting design for large-scale luxury weddings.",
    featured: false,
    verified: true,
  },
  {
    name: "Enchanted Woods Design",
    businessName: "Enchanted Woods",
    email: "events@enchantedwoods.com",
    city: "Bali, Indonesia",
    category: "decorators",
    categories: ["decorators"],
    priceFrom: 45000,
    rating: 4.8,
    reviewCount: 92,
    description: "Bohemian and rustic-luxe decor styling. We use sustainable materials to create magical, Pinterest-worthy setups.",
    featured: false,
    verified: true,
  }
];

async function seed() {
  try {
    console.log("Connecting to MongoDB...");
    await connectDB();
    console.log("Connected.");

    console.log("Clearing existing vendors to ensure a clean state...");
    await Vendor.deleteMany({});
    console.log("Cleared existing vendors.");

    console.log(`Inserting ${vendors.length} vendors...`);
    await Vendor.insertMany(vendors);
    console.log("Successfully seeded vendors!");

    process.exit(0);
  } catch (error) {
    console.error("Error seeding vendors:", error);
    process.exit(1);
  }
}

seed();
