import mongoose from "mongoose";
import { connectDB } from "../lib/mongodb";
import { Vendor } from "../lib/models/Vendor";
import { Venue } from "../lib/models/Venue";
import { ServiceListing } from "../lib/models/ServiceListing";
import { hashPassword } from "../lib/auth";

async function seedMasterVendor() {
  try {
    console.log("Connecting to MongoDB...");
    await connectDB();
    console.log("Connected to MongoDB.");

    // 1. Clear existing collections completely
    console.log("Clearing existing Vendor, Venue, and ServiceListing collections...");
    await Vendor.deleteMany({});
    await Venue.deleteMany({});
    await ServiceListing.deleteMany({});
    console.log("Collections cleared.");

    // 2. Create the master Vendor Account
    console.log("Creating Master Vendor Account...");
    const vendorEmail = "vendor@soulswed.com";
    const plainPassword = "ni$4eDcy!_x)IZ2A";
    const vendorDoc = await Vendor.create({
      name: "Master Vendor",
      businessName: "SoulsWed Premium Collection",
      email: vendorEmail,
      passwordHash: hashPassword(plainPassword),
      city: "Global",
      categories: ["venues", "rooms", "planners", "caterers", "decorators"],
      verified: true,
      available: true,
      featured: true,
    });
    
    const vendorId = vendorDoc._id.toString();
    console.log(`Master Vendor created! ID: ${vendorId}, Email: ${vendorEmail}`);

    // 3. Create the Venues
    const venuesToCreate = [
      {
        venueId: "venue-ritz-1",
        vendorId,
        name: "The Ritz-Carlton New York, NoMad",
        location: "NoMad",
        city: "New York, United States",
        country: "United States",
        type: "Luxury Hotel",
        price: "144000",
        priceUnit: "per day",
        rating: 5,
        reviewCount: 142,
        description: "Experience the ultimate luxury wedding venue at The Ritz-Carlton New York, NoMad.",
        featured: true,
        verified: true,
        active: true,
        indoor: true,
        outdoor: true,
      },
      {
        venueId: "venue-conrad-1",
        vendorId,
        name: "Conrad New York Downtown",
        location: "Downtown",
        city: "New York, United States",
        type: "Luxury Hotel",
        price: "50000",
        priceUnit: "per day",
        rating: 5,
        reviewCount: 98,
        description: "An extraordinary all-suite luxury hotel offering a sophisticated setting.",
        featured: false,
        verified: true,
        active: true,
      },
      {
        venueId: "venue-refinery-1",
        vendorId,
        name: "Refinery Hotel New York",
        location: "Garment District",
        city: "New York, United States",
        type: "Boutique Hotel",
        price: "38000",
        priceUnit: "per day",
        rating: 4.8,
        reviewCount: 65,
        description: "A luxury boutique hotel perfectly blending historic charm and modern elegance.",
        featured: false,
        verified: true,
        active: true,
      },
      {
        venueId: "venue-jw-hk-1",
        vendorId,
        name: "JW Marriott Hotel Hong Kong",
        location: "Admiralty",
        city: "Hong Kong",
        type: "Luxury Hotel",
        price: "27000",
        priceUnit: "per day",
        rating: 4.9,
        reviewCount: 210,
        description: "Celebrate your romance in our spectacular pillar-less ballroom.",
        featured: true,
        verified: true,
        active: true,
      },
      {
        venueId: "venue-intercontinental-hk-1",
        vendorId,
        name: "InterContinental Grand Stanford",
        location: "Kowloon",
        city: "Hong Kong",
        type: "Luxury Hotel",
        price: "17000",
        priceUnit: "per day",
        rating: 4.7,
        reviewCount: 112,
        description: "Stunning Victoria Harbour views and award-winning dining.",
        featured: false,
        verified: true,
        active: true,
      }
    ];

    // 4. Create Venues with Rooms (For "Rooms" category) - Moved to services to match dashboard
    const roomsToCreate = [
      {
        serviceId: "room-plaza-1",
        vendorId,
        category: "rooms",
        name: "The Plaza Hotel - Royal Suite",
        location: "Central Park South",
        city: "New York, United States",
        priceFrom: 120000,
        priceUnit: "per night",
        rating: 5,
        reviewCount: 340,
        description: "Exquisite decor, unparalleled service, and iconic Central Park views.",
        featured: true,
        verified: true,
        active: true,
      },
      {
        serviceId: "room-burj-1",
        vendorId,
        category: "rooms",
        name: "Burj Al Arab - Panoramic Suite",
        location: "Jumeirah",
        city: "Dubai, UAE",
        priceFrom: 95000,
        priceUnit: "per night",
        rating: 5,
        reviewCount: 412,
        description: "A spectacular two-story suite offering uninterrupted views of the Arabian Gulf.",
        featured: true,
        verified: true,
        active: true,
      },
      {
        serviceId: "room-fourseasons-bb-1",
        vendorId,
        category: "rooms",
        name: "Four Seasons - Ocean View Villa",
        location: "Motu Tehotu",
        city: "Bora Bora, French Polynesia",
        priceFrom: 85000,
        priceUnit: "per night",
        rating: 4.9,
        reviewCount: 189,
        description: "Overwater bungalows offering the most romantic setting.",
        featured: false,
        verified: true,
        active: true,
      },
      {
        serviceId: "room-savoy-1",
        vendorId,
        category: "rooms",
        name: "The Savoy - Thames Foyer Suite",
        location: "Strand",
        city: "London, UK",
        priceFrom: 65000,
        priceUnit: "per night",
        rating: 4.8,
        reviewCount: 201,
        description: "Experience Edwardian elegance in the heart of London.",
        featured: false,
        verified: true,
        active: true,
      },
      {
        serviceId: "room-taj-1",
        vendorId,
        category: "rooms",
        name: "Taj Lake Palace - Grand Royal Suite",
        location: "Lake Pichola",
        city: "Udaipur, India",
        priceFrom: 45000,
        priceUnit: "per night",
        rating: 4.9,
        reviewCount: 256,
        description: "Live like royalty in a marble palace floating on Lake Pichola.",
        featured: false,
        verified: true,
        active: true,
      }
    ];

    // 5. Create ServiceListings (Planners, Caterers, Decorators)
    const servicesToCreate = [
      // Planners
      {
        serviceId: "planner-eve-1",
        vendorId,
        category: "planners",
        name: "Eve Experience",
        city: "Kollam, India",
        priceFrom: 260000,
        priceUnit: "per event",
        rating: 4.9,
        reviewCount: 45,
        description: "Enjoy your special day while the experts take care of the details.",
        featured: true,
        verified: true,
        active: true,
      },
      {
        serviceId: "planner-sans-1",
        vendorId,
        category: "planners",
        name: "SANS Events",
        city: "Kochi, India",
        priceFrom: 250000,
        priceUnit: "per event",
        rating: 4.8,
        reviewCount: 38,
        description: "Bringing your vision to life with meticulous planning.",
        featured: true,
        verified: true,
        active: true,
      },
      {
        serviceId: "planner-vows-1",
        vendorId,
        category: "planners",
        name: "Vows & Veils Planning",
        city: "London, UK",
        priceFrom: 350000,
        priceUnit: "per event",
        rating: 5,
        reviewCount: 120,
        description: "Award-winning international wedding planners.",
        featured: false,
        verified: true,
        active: true,
      },
      {
        serviceId: "planner-wdc-1",
        vendorId,
        category: "planners",
        name: "The Wedding Design Company",
        city: "New Delhi, India",
        priceFrom: 400000,
        priceUnit: "per event",
        rating: 4.9,
        reviewCount: 88,
        description: "Curating bespoke luxury weddings.",
        featured: false,
        verified: true,
        active: true,
      },
      {
        serviceId: "planner-luxe-1",
        vendorId,
        category: "planners",
        name: "Luxe Events Co.",
        city: "Dubai, UAE",
        priceFrom: 450000,
        priceUnit: "per event",
        rating: 4.7,
        reviewCount: 52,
        description: "Creating unforgettable, high-profile events.",
        featured: false,
        verified: true,
        active: true,
      },

      // Caterers
      {
        serviceId: "caterer-gastro-1",
        vendorId,
        category: "caterers",
        name: "Gastronomic Excellence",
        city: "Paris, France",
        priceFrom: 18000,
        priceUnit: "per plate",
        rating: 5,
        reviewCount: 130,
        description: "Michelin-starred culinary experiences.",
        featured: true,
        verified: true,
        active: true,
      },
      {
        serviceId: "caterer-royal-1",
        vendorId,
        category: "caterers",
        name: "The Royal Feast",
        city: "Jaipur, India",
        priceFrom: 5500,
        priceUnit: "per plate",
        rating: 4.8,
        reviewCount: 240,
        description: "Authentic, rich, and lavish Indian feasts.",
        featured: true,
        verified: true,
        active: true,
      },
      {
        serviceId: "caterer-global-1",
        vendorId,
        category: "caterers",
        name: "Global Palate Events",
        city: "New York, United States",
        priceFrom: 12500,
        priceUnit: "per plate",
        rating: 4.9,
        reviewCount: 95,
        description: "Customized menus featuring global cuisines.",
        featured: false,
        verified: true,
        active: true,
      },
      {
        serviceId: "caterer-dolce-1",
        vendorId,
        category: "caterers",
        name: "La Dolce Vita Catering",
        city: "Rome, Italy",
        priceFrom: 14000,
        priceUnit: "per plate",
        rating: 4.7,
        reviewCount: 110,
        description: "Bringing the authentic taste of Italy to your celebration.",
        featured: false,
        verified: true,
        active: true,
      },
      {
        serviceId: "caterer-oceanic-1",
        vendorId,
        category: "caterers",
        name: "Oceanic Bites & Bar",
        city: "Sydney, Australia",
        priceFrom: 9500,
        priceUnit: "per plate",
        rating: 4.6,
        reviewCount: 78,
        description: "Premium seafood and modern Australian cuisine.",
        featured: false,
        verified: true,
        active: true,
      },

      // Decorators
      {
        serviceId: "decorator-beretania-1",
        vendorId,
        category: "decorators",
        name: "Beretania Florist",
        city: "Honolulu, United States",
        priceFrom: 29223,
        priceUnit: "per event",
        rating: 4.9,
        reviewCount: 67,
        description: "Stunning tropical floral arrangements.",
        featured: true,
        verified: true,
        active: true,
      },
      {
        serviceId: "decorator-french-1",
        vendorId,
        category: "decorators",
        name: "French Florist",
        city: "California, United States",
        priceFrom: 25048,
        priceUnit: "per event",
        rating: 4.8,
        reviewCount: 115,
        description: "Transforming spaces with elegance.",
        featured: true,
        verified: true,
        active: true,
      },
      {
        serviceId: "decorator-filles-1",
        vendorId,
        category: "decorators",
        name: "Les Filles d'a cote",
        city: "Paris, France",
        priceFrom: 12656,
        priceUnit: "per event",
        rating: 4.7,
        reviewCount: 42,
        description: "Chic and sophisticated Parisian event styling.",
        featured: false,
        verified: true,
        active: true,
      },
      {
        serviceId: "decorator-royal-1",
        vendorId,
        category: "decorators",
        name: "Royal Petals Decor",
        city: "Mumbai, India",
        priceFrom: 85000,
        priceUnit: "per event",
        rating: 4.9,
        reviewCount: 180,
        description: "Extravagant mandaps and majestic setups.",
        featured: false,
        verified: true,
        active: true,
      },
      {
        serviceId: "decorator-enchanted-1",
        vendorId,
        category: "decorators",
        name: "Enchanted Woods Design",
        city: "Bali, Indonesia",
        priceFrom: 45000,
        priceUnit: "per event",
        rating: 4.8,
        reviewCount: 92,
        description: "Bohemian and rustic-luxe decor styling.",
        featured: false,
        verified: true,
        active: true,
      }
    ];

    console.log("Inserting Venues (5 total: 5 Venues)...");
    await Venue.insertMany(venuesToCreate);
    
    console.log("Inserting Services (20 total: 5 Rooms, Planners, Caterers, Decorators)...");
    await ServiceListing.insertMany([...roomsToCreate, ...servicesToCreate]);

    console.log("Successfully seeded master vendor and all 25 listings!");
    process.exit(0);

  } catch (error) {
    console.error("Error seeding master vendor:", error);
    process.exit(1);
  }
}

seedMasterVendor();
