/**
 * VENUE SEED SCRIPT
 * 
 * Migrates all venues from the static venues-data.ts into MongoDB.
 * Run once with: node scripts/seed-venues.mjs
 * 
 * Safe to re-run — uses upsert so it won't create duplicates.
 */

import mongoose from "mongoose";
import * as dotenv from "dotenv";
import { fileURLToPath } from "url";
import { dirname, resolve } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: resolve(__dirname, "../.env") });
dotenv.config({ path: resolve(__dirname, "../.env.local") });

const MONGODB_URI = process.env.MONGODB_URI;
if (!MONGODB_URI) {
  console.error("❌ MONGODB_URI is not set in .env");
  process.exit(1);
}

// ── Inline schema (can't import TS from an mjs script) ──────────────────────
const VenueSchema = new mongoose.Schema({
  venueId:            { type: String, required: true, unique: true },
  name:               { type: String, required: true },
  location:           { type: String },
  city:               { type: String },
  country:            { type: String, default: "Global" },
  type:               { type: String },
  price:              { type: String },
  priceUnit:          { type: String },
  pricePerPlateVeg:   { type: String },
  pricePerPlateNonVeg:{ type: String },
  rentalCost:         { type: String },
  rating:             { type: Number, default: 0 },
  reviewCount:        { type: Number, default: 0 },
  verified:           { type: Boolean, default: false },
  featured:           { type: Boolean, default: false },
  image:              { type: String },
  gallery:            [{ type: String }],
  minGuests:          { type: Number },
  maxGuests:          { type: Number },
  rooms:              { type: Number, default: 0 },
  outdoor:            { type: Boolean, default: false },
  indoor:             { type: Boolean, default: true },
  parking:            { type: Boolean, default: false },
  catering:           { type: Boolean, default: false },
  description:        { type: String },
  features:           [{ type: String }],
  faqs:               [{ question: String, answer: String }],
  reviews:            [{ id: Number, author: String, avatar: String, date: String, rating: Number, text: String }],
  active:             { type: Boolean, default: true },
  createdAt:          { type: Date, default: Date.now },
  updatedAt:          { type: Date, default: Date.now },
});

// ── Venue data (copied from venues-data.ts) ──────────────────────────────────
const venues = [
  {
    id: "venue-paris-1",
    name: "Château de Chantilly",
    location: "Paris Center",
    city: "Paris",
    country: "Global",
    type: "Historic Château",
    price: "₹335840",
    priceUnit: "per day",
    pricePerPlateVeg: "₹5695",
    pricePerPlateNonVeg: "₹10161",
    rentalCost: "₹344724",
    rating: 4.7,
    reviewCount: 98,
    verified: true,
    featured: true,
    image: "/images/venues/93e4edb0efd7ac902c480f49cdbf2697.webp",
    gallery: ["/images/venues/53234027fb9a7ac30ab05a227a7b4d90.webp","/images/venues/49af563c5438f875cce1dc86be62f43a.webp","/images/venues/6d1fc06392014fe21e78ccdec409943a.jpg"],
    minGuests: 122, maxGuests: 468, rooms: 68, outdoor: true, indoor: true, parking: true, catering: true,
    description: "A majestic French château offering aristocratic elegance, vast manicured gardens, and opulent ballrooms for a truly royal wedding.",
    features: ["Valet Parking","In-house Catering","Bridal Suite","AV & Lighting","Concierge Service","Scenic Views"],
    faqs: [{question:"What is the minimum guest count?",answer:"We accommodate weddings from 50 guests."},{question:"Is outside catering allowed?",answer:"We have an exclusive in-house catering team."}],
    reviews: [{id:1,author:"A Happy Couple",avatar:"A",date:"April 2025",rating:5,text:"A truly unforgettable experience. Highly recommended!"}],
  },
  {
    id: "venue-paris-2",
    name: "The Peninsula Paris",
    location: "Paris Center",
    city: "Paris",
    country: "Global",
    type: "5-Star Hotel",
    price: "₹278251",
    priceUnit: "per day",
    pricePerPlateVeg: "₹7624",
    pricePerPlateNonVeg: "₹8342",
    rentalCost: "₹264240",
    rating: 4.9,
    reviewCount: 233,
    verified: true,
    featured: false,
    image: "/images/venues/fef86b75f570fac8263f4e2b8bac059e.jpg",
    gallery: ["/images/venues/fef86b75f570fac8263f4e2b8bac059e.jpg","/images/venues/813dae52a08423236cc5de46d9f2e4d5.jpg","/images/venues/bc8fc7031d971fe6477313cdee412bfc.jpg"],
    minGuests: 103, maxGuests: 934, rooms: 112, outdoor: true, indoor: true, parking: true, catering: true,
    description: "Located steps from the Arc de Triomphe, offering rooftop views of the Eiffel Tower and exquisite Parisian gastronomy.",
    features: ["Valet Parking","In-house Catering","Bridal Suite","AV & Lighting","Concierge Service","Scenic Views"],
    faqs: [{question:"What is the minimum guest count?",answer:"We accommodate weddings from 50 guests."},{question:"Is outside catering allowed?",answer:"We have an exclusive in-house catering team."}],
    reviews: [{id:1,author:"A Happy Couple",avatar:"A",date:"April 2025",rating:5,text:"A truly unforgettable experience. Highly recommended!"}],
  },
  {
    id: "venue-paris-3",
    name: "Hôtel Ritz Paris",
    location: "Paris Center",
    city: "Paris",
    country: "Global",
    type: "Luxury Palace",
    price: "₹269205",
    priceUnit: "per day",
    pricePerPlateVeg: "₹5460",
    pricePerPlateNonVeg: "₹7221",
    rentalCost: "₹302485",
    rating: 4.6,
    reviewCount: 164,
    verified: true,
    featured: false,
    image: "/images/venues/813dae52a08423236cc5de46d9f2e4d5.jpg",
    gallery: ["/images/venues/813dae52a08423236cc5de46d9f2e4d5.jpg","/images/venues/bc8fc7031d971fe6477313cdee412bfc.jpg","/images/venues/fef86b75f570fac8263f4e2b8bac059e.jpg"],
    minGuests: 58, maxGuests: 733, rooms: 121, outdoor: true, indoor: true, parking: true, catering: true,
    description: "The epitome of French art de vivre. Host your reception in the legendary Grand Jardin or the lavish Salon Vendôme.",
    features: ["Valet Parking","In-house Catering","Bridal Suite","AV & Lighting","Concierge Service","Scenic Views"],
    faqs: [{question:"What is the minimum guest count?",answer:"We accommodate weddings from 50 guests."},{question:"Is outside catering allowed?",answer:"We have an exclusive in-house catering team."}],
    reviews: [{id:1,author:"A Happy Couple",avatar:"A",date:"April 2025",rating:5,text:"A truly unforgettable experience. Highly recommended!"}],
  },
  {
    id: "venue-new-york-1",
    name: "The Plaza Hotel",
    location: "New York Center",
    city: "New York",
    country: "Global",
    type: "Historic Luxury",
    price: "₹253972",
    priceUnit: "per day",
    pricePerPlateVeg: "₹5274",
    pricePerPlateNonVeg: "₹10193",
    rentalCost: "₹344904",
    rating: 4.7,
    reviewCount: 230,
    verified: true,
    featured: true,
    image: "/images/venues/b1ea9c403e0b88139c71eaa449a366d8.webp",
    gallery: ["/images/venues/4c6d330355a38b37569cd227bcef593a.webp","/images/venues/9c8c6c14cea93182566c4c5258d97d1d.webp","/images/venues/8728061205a5d7f11820ef4e6c7d79c2.webp"],
    minGuests: 78, maxGuests: 387, rooms: 25, outdoor: true, indoor: true, parking: true, catering: true,
    description: "An iconic Manhattan landmark. The Grand Ballroom provides a legendary, fairy-tale setting for the ultimate New York wedding.",
    features: ["Valet Parking","In-house Catering","Bridal Suite","AV & Lighting","Concierge Service","Scenic Views"],
    faqs: [{question:"What is the minimum guest count?",answer:"We accommodate weddings from 50 guests."},{question:"Is outside catering allowed?",answer:"We have an exclusive in-house catering team."}],
    reviews: [{id:1,author:"A Happy Couple",avatar:"A",date:"April 2025",rating:5,text:"A truly unforgettable experience. Highly recommended!"}],
  },
  {
    id: "venue-new-york-2",
    name: "Tribeca Rooftop",
    location: "New York SoHo",
    city: "New York",
    country: "Global",
    type: "Rooftop Venue",
    price: "₹159614",
    priceUnit: "per day",
    pricePerPlateVeg: "₹6016",
    pricePerPlateNonVeg: "₹7948",
    rentalCost: "₹168988",
    rating: 4.5,
    reviewCount: 147,
    verified: true,
    featured: false,
    image: "/images/venues/9c8c6c14cea93182566c4c5258d97d1d.webp",
    gallery: ["/images/venues/8728061205a5d7f11820ef4e6c7d79c2.webp","/images/venues/b1ea9c403e0b88139c71eaa449a366d8.webp","/images/venues/4c6d330355a38b37569cd227bcef593a.webp"],
    minGuests: 87, maxGuests: 512, rooms: 0, outdoor: true, indoor: false, parking: false, catering: true,
    description: "A chic Manhattan rooftop with breathtaking skyline views. Perfect for cocktail receptions and modern, urban celebrations.",
    features: ["Rooftop Access","In-house Catering","AV & Lighting","NYC Skyline Views","Bar Service"],
    faqs: [{question:"Is the venue weather-dependent?",answer:"We have retractable covers for inclement weather."},{question:"Can we bring our own DJ?",answer:"Yes, external entertainment is permitted."}],
    reviews: [{id:1,author:"A Happy Couple",avatar:"A",date:"March 2025",rating:5,text:"The views were absolutely spectacular!"}],
  },
  {
    id: "venue-new-york-3",
    name: "Brooklyn Botanic Garden",
    location: "New York Brooklyn",
    city: "New York",
    country: "Global",
    type: "Botanical Garden",
    price: "₹212948",
    priceUnit: "per day",
    pricePerPlateVeg: "₹8310",
    pricePerPlateNonVeg: "₹9890",
    rentalCost: "₹219300",
    rating: 4.8,
    reviewCount: 189,
    verified: true,
    featured: false,
    image: "/images/venues/8728061205a5d7f11820ef4e6c7d79c2.webp",
    gallery: ["/images/venues/4c6d330355a38b37569cd227bcef593a.webp","/images/venues/b1ea9c403e0b88139c71eaa449a366d8.webp","/images/venues/9c8c6c14cea93182566c4c5258d97d1d.webp"],
    minGuests: 50, maxGuests: 300, rooms: 0, outdoor: true, indoor: true, parking: true, catering: false,
    description: "A serene urban oasis in Brooklyn featuring cherry blossoms, Japanese gardens, and a glass-enclosed pavilion for intimate celebrations.",
    features: ["Garden Access","AV & Lighting","Scenic Views","Parking","Bridal Suite"],
    faqs: [{question:"Is outside catering allowed?",answer:"Yes, we have a list of approved caterers."},{question:"What is the capacity?",answer:"Up to 300 guests in our main pavilion."}],
    reviews: [{id:1,author:"A Happy Couple",avatar:"A",date:"May 2025",rating:5,text:"Magical garden setting — our guests were amazed."}],
  },
  {
    id: "venue-london-1",
    name: "Kensington Palace",
    location: "London Kensington",
    city: "London",
    country: "Global",
    type: "Royal Palace",
    price: "₹418500",
    priceUnit: "per day",
    pricePerPlateVeg: "₹9200",
    pricePerPlateNonVeg: "₹12400",
    rentalCost: "₹430000",
    rating: 4.9,
    reviewCount: 312,
    verified: true,
    featured: true,
    image: "/images/venues/bc8fc7031d971fe6477313cdee412bfc.jpg",
    gallery: ["/images/venues/53234027fb9a7ac30ab05a227a7b4d90.webp","/images/venues/49af563c5438f875cce1dc86be62f43a.webp","/images/venues/93e4edb0efd7ac902c480f49cdbf2697.webp"],
    minGuests: 100, maxGuests: 800, rooms: 200, outdoor: true, indoor: true, parking: true, catering: true,
    description: "Host your wedding in the grandeur of a royal palace. Kensington's staterooms and manicured gardens offer a truly regal experience.",
    features: ["Valet Parking","In-house Catering","Bridal Suite","Royal Gardens","AV & Lighting","Security"],
    faqs: [{question:"Can we access the public areas?",answer:"Private sections are reserved for your event."},{question:"Is catering exclusive?",answer:"We work with approved royal caterers."}],
    reviews: [{id:1,author:"A Happy Couple",avatar:"A",date:"June 2025",rating:5,text:"A once-in-a-lifetime experience — fit for royalty!"}],
  },
  {
    id: "venue-london-2",
    name: "The Savoy Hotel",
    location: "London Strand",
    city: "London",
    country: "Global",
    type: "5-Star Hotel",
    price: "₹362000",
    priceUnit: "per day",
    pricePerPlateVeg: "₹7800",
    pricePerPlateNonVeg: "₹10500",
    rentalCost: "₹380000",
    rating: 4.8,
    reviewCount: 267,
    verified: true,
    featured: false,
    image: "/images/venues/49af563c5438f875cce1dc86be62f43a.webp",
    gallery: ["/images/venues/bc8fc7031d971fe6477313cdee412bfc.jpg","/images/venues/813dae52a08423236cc5de46d9f2e4d5.jpg","/images/venues/fef86b75f570fac8263f4e2b8bac059e.jpg"],
    minGuests: 80, maxGuests: 600, rooms: 267, outdoor: false, indoor: true, parking: true, catering: true,
    description: "London's most iconic address on the Strand. The Lancaster Ballroom and Thames Foyer provide unrivalled elegance for any celebration.",
    features: ["Valet Parking","In-house Catering","Bridal Suite","AV & Lighting","Concierge","Thames Views"],
    faqs: [{question:"What is the minimum booking?",answer:"We require a minimum of 80 guests for event hire."},{question:"Do you offer wedding packages?",answer:"Yes, our events team can create bespoke packages."}],
    reviews: [{id:1,author:"A Happy Couple",avatar:"A",date:"April 2025",rating:5,text:"Absolutely stunning venue — service was flawless."}],
  },
  {
    id: "venue-london-3",
    name: "Syon Park",
    location: "London Richmond",
    city: "London",
    country: "Global",
    type: "Country Estate",
    price: "₹290000",
    priceUnit: "per day",
    pricePerPlateVeg: "₹6500",
    pricePerPlateNonVeg: "₹9000",
    rentalCost: "₹310000",
    rating: 4.6,
    reviewCount: 141,
    verified: true,
    featured: false,
    image: "/images/venues/53234027fb9a7ac30ab05a227a7b4d90.webp",
    gallery: ["/images/venues/93e4edb0efd7ac902c480f49cdbf2697.webp","/images/venues/bc8fc7031d971fe6477313cdee412bfc.jpg","/images/venues/49af563c5438f875cce1dc86be62f43a.webp"],
    minGuests: 60, maxGuests: 500, rooms: 40, outdoor: true, indoor: true, parking: true, catering: false,
    description: "A magnificent Tudor estate with 200 acres of parkland on the Thames. Syon's Great Conservatory is a spectacular glass-domed reception space.",
    features: ["Parkland Access","Glass Conservatory","Scenic Views","Parking","Historic Rooms"],
    faqs: [{question:"Is the estate exclusive for our event?",answer:"Yes, full exclusive hire is available."},{question:"Can we use external caterers?",answer:"Yes, we have a list of approved suppliers."}],
    reviews: [{id:1,author:"A Happy Couple",avatar:"A",date:"May 2025",rating:5,text:"The grounds were breathtaking — so many great photos!"}],
  },
  {
    id: "venue-dubai-1",
    name: "Burj Al Arab",
    location: "Dubai Jumeirah",
    city: "Dubai",
    country: "Global",
    type: "Luxury Hotel",
    price: "₹850000",
    priceUnit: "per day",
    pricePerPlateVeg: "₹15000",
    pricePerPlateNonVeg: "₹22000",
    rentalCost: "₹900000",
    rating: 5.0,
    reviewCount: 421,
    verified: true,
    featured: true,
    image: "/images/venues/6d1fc06392014fe21e78ccdec409943a.jpg",
    gallery: ["/images/venues/93e4edb0efd7ac902c480f49cdbf2697.webp","/images/venues/b1ea9c403e0b88139c71eaa449a366d8.webp","/images/venues/fef86b75f570fac8263f4e2b8bac059e.jpg"],
    minGuests: 100, maxGuests: 500, rooms: 202, outdoor: true, indoor: true, parking: true, catering: true,
    description: "The world's most luxurious hotel — a sail-shaped icon on its own private island. An unrivalled statement of opulence for the ultimate wedding.",
    features: ["Private Island","Helicopter Access","Butler Service","Bridal Suite","Underwater Restaurant","Pool Deck"],
    faqs: [{question:"Is helicopter arrival available?",answer:"Yes, we have a dedicated helipad on the roof."},{question:"Are there suite options?",answer:"All 202 suites are available for guest accommodation."}],
    reviews: [{id:1,author:"A Happy Couple",avatar:"A",date:"January 2025",rating:5,text:"There are no words — beyond a dream wedding venue."}],
  },
  {
    id: "venue-dubai-2",
    name: "Atlantis The Palm",
    location: "Dubai Palm Jumeirah",
    city: "Dubai",
    country: "Global",
    type: "Resort",
    price: "₹620000",
    priceUnit: "per day",
    pricePerPlateVeg: "₹12000",
    pricePerPlateNonVeg: "₹18000",
    rentalCost: "₹650000",
    rating: 4.8,
    reviewCount: 356,
    verified: true,
    featured: false,
    image: "/images/venues/b1ea9c403e0b88139c71eaa449a366d8.webp",
    gallery: ["/images/venues/4c6d330355a38b37569cd227bcef593a.webp","/images/venues/8728061205a5d7f11820ef4e6c7d79c2.webp","/images/venues/9c8c6c14cea93182566c4c5258d97d1d.webp"],
    minGuests: 150, maxGuests: 2000, rooms: 1548, outdoor: true, indoor: true, parking: true, catering: true,
    description: "Dubai's most iconic resort on the Palm. From beachfront ceremonies to grand ballrooms, Atlantis offers unmatched scale and luxury.",
    features: ["Beach Ceremony","Grand Ballroom","Aquaventure Access","Bridal Suite","AV & Lighting","Multiple Restaurants"],
    faqs: [{question:"What is the maximum capacity?",answer:"Our Grand Ballroom holds up to 2,000 guests."},{question:"Is the aquapark included?",answer:"Private access can be arranged for your guests."}],
    reviews: [{id:1,author:"A Happy Couple",avatar:"A",date:"February 2025",rating:5,text:"The perfect blend of luxury and fun. Truly spectacular!"}],
  },
  {
    id: "venue-dubai-3",
    name: "Four Seasons Resort Dubai",
    location: "Dubai Jumeirah Beach",
    city: "Dubai",
    country: "Global",
    type: "Beach Resort",
    price: "₹480000",
    priceUnit: "per day",
    pricePerPlateVeg: "₹10000",
    pricePerPlateNonVeg: "₹16000",
    rentalCost: "₹510000",
    rating: 4.7,
    reviewCount: 198,
    verified: true,
    featured: false,
    image: "/images/venues/4c6d330355a38b37569cd227bcef593a.webp",
    gallery: ["/images/venues/9c8c6c14cea93182566c4c5258d97d1d.webp","/images/venues/b1ea9c403e0b88139c71eaa449a366d8.webp","/images/venues/8728061205a5d7f11820ef4e6c7d79c2.webp"],
    minGuests: 50, maxGuests: 800, rooms: 237, outdoor: true, indoor: true, parking: true, catering: true,
    description: "Pristine beach ceremonies with Arabian Gulf sunsets. The Four Seasons combines natural beauty with impeccable service.",
    features: ["Beach Ceremony","Poolside Receptions","Bridal Suite","AV & Lighting","Sunset Views","Spa Access"],
    faqs: [{question:"Is a beach ceremony available?",answer:"Yes, we have a dedicated beach ceremony setup."},{question:"Can we customize the menu?",answer:"Our culinary team creates bespoke wedding menus."}],
    reviews: [{id:1,author:"A Happy Couple",avatar:"A",date:"March 2025",rating:5,text:"The sunset ceremony was everything we dreamed of!"}],
  },
  {
    id: "venue-tokyo-1",
    name: "The Ritz-Carlton Tokyo",
    location: "Tokyo Roppongi",
    city: "Tokyo",
    country: "Global",
    type: "5-Star Hotel",
    price: "₹395000",
    priceUnit: "per day",
    pricePerPlateVeg: "₹8500",
    pricePerPlateNonVeg: "₹13000",
    rentalCost: "₹420000",
    rating: 4.9,
    reviewCount: 278,
    verified: true,
    featured: true,
    image: "/images/venues/bc8fc7031d971fe6477313cdee412bfc.jpg",
    gallery: ["/images/venues/fef86b75f570fac8263f4e2b8bac059e.jpg","/images/venues/813dae52a08423236cc5de46d9f2e4d5.jpg","/images/venues/53234027fb9a7ac30ab05a227a7b4d90.webp"],
    minGuests: 60, maxGuests: 450, rooms: 248, outdoor: false, indoor: true, parking: true, catering: true,
    description: "45 floors above Tokyo, the Ritz-Carlton offers a dramatic cityscape backdrop with Japan's legendary hospitality for your wedding day.",
    features: ["Mt Fuji Views","In-house Catering","Bridal Suite","AV & Lighting","Spa Access","Concierge"],
    faqs: [{question:"Can we see Mt Fuji from the venue?",answer:"On clear days, the views of Mt Fuji are breathtaking."},{question:"Do you offer traditional Japanese ceremonies?",answer:"Yes, we can arrange Shinto ceremony elements."}],
    reviews: [{id:1,author:"A Happy Couple",avatar:"A",date:"April 2025",rating:5,text:"The views of Tokyo at night were simply magical."}],
  },
  {
    id: "venue-tokyo-2",
    name: "Meiji Jingu Shrine Garden",
    location: "Tokyo Harajuku",
    city: "Tokyo",
    country: "Global",
    type: "Traditional Shrine",
    price: "₹185000",
    priceUnit: "per day",
    pricePerPlateVeg: "₹5200",
    pricePerPlateNonVeg: "₹8000",
    rentalCost: "₹200000",
    rating: 4.8,
    reviewCount: 203,
    verified: true,
    featured: false,
    image: "/images/venues/813dae52a08423236cc5de46d9f2e4d5.jpg",
    gallery: ["/images/venues/bc8fc7031d971fe6477313cdee412bfc.jpg","/images/venues/fef86b75f570fac8263f4e2b8bac059e.jpg","/images/venues/53234027fb9a7ac30ab05a227a7b4d90.webp"],
    minGuests: 20, maxGuests: 200, rooms: 0, outdoor: true, indoor: false, parking: true, catering: false,
    description: "Exchange vows surrounded by 100,000 trees in the heart of Tokyo. A Shinto ceremony at Meiji Jingu is a deeply spiritual and uniquely Japanese experience.",
    features: ["Traditional Ceremony","Forest Setting","Bridal Kimono Service","Photography Access"],
    faqs: [{question:"Can non-Japanese couples use the shrine?",answer:"Yes, the shrine welcomes couples of all backgrounds."},{question:"What dress code is expected?",answer:"Traditional or formal Western attire is appropriate."}],
    reviews: [{id:1,author:"A Happy Couple",avatar:"A",date:"March 2025",rating:5,text:"Our Shinto ceremony was the most moving experience of our lives."}],
  },
  {
    id: "venue-tokyo-3",
    name: "Palace Hotel Tokyo",
    location: "Tokyo Marunouchi",
    city: "Tokyo",
    country: "Global",
    type: "Urban Luxury Hotel",
    price: "₹310000",
    priceUnit: "per day",
    pricePerPlateVeg: "₹7200",
    pricePerPlateNonVeg: "₹11000",
    rentalCost: "₹330000",
    rating: 4.7,
    reviewCount: 165,
    verified: true,
    featured: false,
    image: "/images/venues/fef86b75f570fac8263f4e2b8bac059e.jpg",
    gallery: ["/images/venues/813dae52a08423236cc5de46d9f2e4d5.jpg","/images/venues/bc8fc7031d971fe6477313cdee412bfc.jpg","/images/venues/53234027fb9a7ac30ab05a227a7b4d90.webp"],
    minGuests: 40, maxGuests: 600, rooms: 290, outdoor: true, indoor: true, parking: true, catering: true,
    description: "Overlooking the Imperial Palace gardens, this hotel blends modern elegance with breathtaking views for an exceptional Tokyo wedding.",
    features: ["Imperial Gardens View","In-house Catering","Bridal Suite","AV & Lighting","Concierge","Multiple Ballrooms"],
    faqs: [{question:"Can we see the Imperial Palace?",answer:"Yes, our garden-view rooms overlook the palace."},{question:"Are there multiple event spaces?",answer:"Yes, we have 5 event spaces of varying capacities."}],
    reviews: [{id:1,author:"A Happy Couple",avatar:"A",date:"February 2025",rating:5,text:"Impeccable service and stunning views — a perfect wedding!"}],
  },
  {
    id: "venue-rome-1",
    name: "Villa Borghese",
    location: "Rome City Center",
    city: "Rome",
    country: "Global",
    type: "Historic Villa",
    price: "₹290000",
    priceUnit: "per day",
    pricePerPlateVeg: "₹6800",
    pricePerPlateNonVeg: "₹9500",
    rentalCost: "₹310000",
    rating: 4.8,
    reviewCount: 234,
    verified: true,
    featured: true,
    image: "/images/venues/93e4edb0efd7ac902c480f49cdbf2697.webp",
    gallery: ["/images/venues/53234027fb9a7ac30ab05a227a7b4d90.webp","/images/venues/6d1fc06392014fe21e78ccdec409943a.jpg","/images/venues/49af563c5438f875cce1dc86be62f43a.webp"],
    minGuests: 50, maxGuests: 500, rooms: 0, outdoor: true, indoor: true, parking: true, catering: false,
    description: "A Renaissance jewel nestled within Rome's most famous park. Ornate frescoes, fountains, and sculpture gardens create an unparalleled backdrop.",
    features: ["Park Access","Garden Terrace","AV & Lighting","Scenic Views","Historic Rooms"],
    faqs: [{question:"Is external catering permitted?",answer:"Yes, from our approved list of Roman caterers."},{question:"Can we have a ceremony in the gardens?",answer:"Yes, garden ceremonies are our specialty."}],
    reviews: [{id:1,author:"A Happy Couple",avatar:"A",date:"May 2025",rating:5,text:"Rome is already magical — Villa Borghese made it extraordinary."}],
  },
  {
    id: "venue-rome-2",
    name: "Hotel de Russie",
    location: "Rome Piazza del Popolo",
    city: "Rome",
    country: "Global",
    type: "5-Star Hotel",
    price: "₹340000",
    priceUnit: "per day",
    pricePerPlateVeg: "₹7500",
    pricePerPlateNonVeg: "₹11000",
    rentalCost: "₹360000",
    rating: 4.7,
    reviewCount: 189,
    verified: true,
    featured: false,
    image: "/images/venues/49af563c5438f875cce1dc86be62f43a.webp",
    gallery: ["/images/venues/93e4edb0efd7ac902c480f49cdbf2697.webp","/images/venues/6d1fc06392014fe21e78ccdec409943a.jpg","/images/venues/53234027fb9a7ac30ab05a227a7b4d90.webp"],
    minGuests: 40, maxGuests: 400, rooms: 122, outdoor: true, indoor: true, parking: true, catering: true,
    description: "A Rocco Forte gem steps from the Villa Borghese. Its Secret Garden is Rome's most coveted outdoor wedding space.",
    features: ["Secret Garden","In-house Catering","Bridal Suite","AV & Lighting","Concierge","Rooftop Terrace"],
    faqs: [{question:"What makes the Secret Garden special?",answer:"It's a terraced garden with cascading roses and a historic fountain."},{question:"Is accommodation included?",answer:"Room blocks can be reserved for wedding guests."}],
    reviews: [{id:1,author:"A Happy Couple",avatar:"A",date:"June 2025",rating:5,text:"The Secret Garden ceremony was worth every penny."}],
  },
  {
    id: "venue-rome-3",
    name: "Castel Sant'Angelo Terrace",
    location: "Rome Vatican",
    city: "Rome",
    country: "Global",
    type: "Historic Castle",
    price: "₹450000",
    priceUnit: "per day",
    pricePerPlateVeg: "₹9000",
    pricePerPlateNonVeg: "₹14000",
    rentalCost: "₹480000",
    rating: 4.9,
    reviewCount: 143,
    verified: true,
    featured: false,
    image: "/images/venues/6d1fc06392014fe21e78ccdec409943a.jpg",
    gallery: ["/images/venues/49af563c5438f875cce1dc86be62f43a.webp","/images/venues/93e4edb0efd7ac902c480f49cdbf2697.webp","/images/venues/53234027fb9a7ac30ab05a227a7b4d90.webp"],
    minGuests: 30, maxGuests: 250, rooms: 0, outdoor: true, indoor: false, parking: false, catering: true,
    description: "Marry atop a 2,000-year-old Roman fortress with panoramic views of the Tiber, Vatican, and ancient city. An utterly unique and romantic setting.",
    features: ["2000yr Old Fortress","Panoramic Views","In-house Catering","Historic Setting","Sunset Ceremonies"],
    faqs: [{question:"Is the venue accessible?",answer:"There is elevator access to the terrace level."},{question:"How large is the terrace?",answer:"The Angel Terrace accommodates up to 250 guests."}],
    reviews: [{id:1,author:"A Happy Couple",avatar:"A",date:"April 2025",rating:5,text:"The most romantic spot in Rome — history all around you."}],
  },
  {
    id: "venue-bali-1",
    name: "Amandari Resort",
    location: "Bali Ubud",
    city: "Bali",
    country: "Global",
    type: "Jungle Resort",
    price: "₹320000",
    priceUnit: "per day",
    pricePerPlateVeg: "₹7000",
    pricePerPlateNonVeg: "₹10500",
    rentalCost: "₹340000",
    rating: 4.9,
    reviewCount: 302,
    verified: true,
    featured: true,
    image: "/images/venues/bc8fc7031d971fe6477313cdee412bfc.jpg",
    gallery: ["/images/venues/813dae52a08423236cc5de46d9f2e4d5.jpg","/images/venues/fef86b75f570fac8263f4e2b8bac059e.jpg","/images/venues/49af563c5438f875cce1dc86be62f43a.webp"],
    minGuests: 20, maxGuests: 150, rooms: 30, outdoor: true, indoor: false, parking: true, catering: true,
    description: "Perched above the sacred Ayung River gorge, Amandari offers a deeply intimate jungle wedding with Balinese ceremonies and rice terrace views.",
    features: ["Rice Terrace Views","Balinese Ceremony","Infinity Pool","In-house Catering","Jungle Setting","Spa"],
    faqs: [{question:"Can we have a traditional Balinese ceremony?",answer:"Yes, we have resident priests who perform blessings."},{question:"How private is the resort?",answer:"Exclusive hire is available for full privacy."}],
    reviews: [{id:1,author:"A Happy Couple",avatar:"A",date:"January 2025",rating:5,text:"A spiritual, natural, and utterly beautiful wedding experience."}],
  },
  {
    id: "venue-bali-2",
    name: "Alila Villas Uluwatu",
    location: "Bali Uluwatu",
    city: "Bali",
    country: "Global",
    type: "Clifftop Villa",
    price: "₹280000",
    priceUnit: "per day",
    pricePerPlateVeg: "₹6500",
    pricePerPlateNonVeg: "₹9800",
    rentalCost: "₹300000",
    rating: 4.8,
    reviewCount: 267,
    verified: true,
    featured: false,
    image: "/images/venues/813dae52a08423236cc5de46d9f2e4d5.jpg",
    gallery: ["/images/venues/bc8fc7031d971fe6477313cdee412bfc.jpg","/images/venues/fef86b75f570fac8263f4e2b8bac059e.jpg","/images/venues/49af563c5438f875cce1dc86be62f43a.webp"],
    minGuests: 10, maxGuests: 120, rooms: 66, outdoor: true, indoor: false, parking: true, catering: true,
    description: "Dramatic clifftop villas overlooking the Indian Ocean. Sunset ceremonies at Alila Uluwatu are among Bali's most iconic wedding experiences.",
    features: ["Ocean Cliffs","Sunset Ceremony","Infinity Pool","In-house Catering","Villa Accommodation"],
    faqs: [{question:"Is there a sunset ceremony option?",answer:"Yes, this is our most requested wedding setup."},{question:"What is the weather like?",answer:"Dry season (April-October) is ideal for outdoor ceremonies."}],
    reviews: [{id:1,author:"A Happy Couple",avatar:"A",date:"March 2025",rating:5,text:"The sunset was unreal — a perfect ending to a perfect day."}],
  },
  {
    id: "venue-bali-3",
    name: "COMO Uma Canggu",
    location: "Bali Canggu",
    city: "Bali",
    country: "Global",
    type: "Beach Club Resort",
    price: "₹195000",
    priceUnit: "per day",
    pricePerPlateVeg: "₹5000",
    pricePerPlateNonVeg: "₹7800",
    rentalCost: "₹215000",
    rating: 4.6,
    reviewCount: 178,
    verified: true,
    featured: false,
    image: "/images/venues/fef86b75f570fac8263f4e2b8bac059e.jpg",
    gallery: ["/images/venues/813dae52a08423236cc5de46d9f2e4d5.jpg","/images/venues/bc8fc7031d971fe6477313cdee412bfc.jpg","/images/venues/53234027fb9a7ac30ab05a227a7b4d90.webp"],
    minGuests: 20, maxGuests: 200, rooms: 119, outdoor: true, indoor: true, parking: true, catering: true,
    description: "A stylish surf-side resort in Canggu with a bohemian, laid-back atmosphere. Perfect for couples seeking a relaxed beach wedding.",
    features: ["Beachfront","Rooftop Pool","In-house Catering","AV & Lighting","Surf Access","Bohemian Vibe"],
    faqs: [{question:"Is the beach ceremony licensed?",answer:"Yes, we handle all permits for beach ceremonies."},{question:"Can we have a boho-themed wedding?",answer:"Absolutely — it's what Canggu is famous for!"}],
    reviews: [{id:1,author:"A Happy Couple",avatar:"A",date:"February 2025",rating:5,text:"Laid-back, beautiful, and absolutely perfect for us."}],
  },
  {
    id: "venue-sydney-1",
    name: "Quay Restaurant",
    location: "Sydney The Rocks",
    city: "Sydney",
    country: "Global",
    type: "Waterfront Restaurant",
    price: "₹245000",
    priceUnit: "per day",
    pricePerPlateVeg: "₹6200",
    pricePerPlateNonVeg: "₹9500",
    rentalCost: "₹260000",
    rating: 4.8,
    reviewCount: 189,
    verified: true,
    featured: true,
    image: "/images/venues/9c8c6c14cea93182566c4c5258d97d1d.webp",
    gallery: ["/images/venues/4c6d330355a38b37569cd227bcef593a.webp","/images/venues/8728061205a5d7f11820ef4e6c7d79c2.webp","/images/venues/b1ea9c403e0b88139c71eaa449a366d8.webp"],
    minGuests: 20, maxGuests: 220, rooms: 0, outdoor: false, indoor: true, parking: false, catering: true,
    description: "Australia's most celebrated fine dining destination. Intimate wedding receptions with front-row views of the Sydney Opera House and Harbour Bridge.",
    features: ["Harbour Bridge View","Opera House View","Fine Dining","AV & Lighting","Concierge","Private Dining"],
    faqs: [{question:"What is the view like?",answer:"Direct waterfront views of the Harbour Bridge and Opera House."},{question:"Is the menu customisable?",answer:"Yes, we create bespoke wedding tasting menus."}],
    reviews: [{id:1,author:"A Happy Couple",avatar:"A",date:"April 2025",rating:5,text:"The view, the food, the service — absolute perfection."}],
  },
  {
    id: "venue-sydney-2",
    name: "Taronga Zoo Roar and Snore",
    location: "Sydney Mosman",
    city: "Sydney",
    country: "Global",
    type: "Zoo Venue",
    price: "₹175000",
    priceUnit: "per day",
    pricePerPlateVeg: "₹4800",
    pricePerPlateNonVeg: "₹7200",
    rentalCost: "₹190000",
    rating: 4.5,
    reviewCount: 134,
    verified: true,
    featured: false,
    image: "/images/venues/8728061205a5d7f11820ef4e6c7d79c2.webp",
    gallery: ["/images/venues/9c8c6c14cea93182566c4c5258d97d1d.webp","/images/venues/4c6d330355a38b37569cd227bcef593a.webp","/images/venues/b1ea9c403e0b88139c71eaa449a366d8.webp"],
    minGuests: 50, maxGuests: 400, rooms: 0, outdoor: true, indoor: false, parking: true, catering: true,
    description: "A truly unique Sydney experience — celebrate your wedding surrounded by wildlife with iconic harbour views from the zoo's elevated position.",
    features: ["Wildlife Encounters","Harbour Views","Outdoor Setting","In-house Catering","Unique Experience"],
    faqs: [{question:"Are animals present during the event?",answer:"Yes, animal encounters can be arranged."},{question:"Is it weather dependent?",answer:"We have contingency marquee setups for wet weather."}],
    reviews: [{id:1,author:"A Happy Couple",avatar:"A",date:"March 2025",rating:5,text:"Absolutely unique — our guests still talk about it!"}],
  },
  {
    id: "venue-sydney-3",
    name: "Doltone House Jones Bay",
    location: "Sydney Pyrmont",
    city: "Sydney",
    country: "Global",
    type: "Waterfront Event Centre",
    price: "₹210000",
    priceUnit: "per day",
    pricePerPlateVeg: "₹5500",
    pricePerPlateNonVeg: "₹8200",
    rentalCost: "₹225000",
    rating: 4.7,
    reviewCount: 212,
    verified: true,
    featured: false,
    image: "/images/venues/4c6d330355a38b37569cd227bcef593a.webp",
    gallery: ["/images/venues/9c8c6c14cea93182566c4c5258d97d1d.webp","/images/venues/8728061205a5d7f11820ef4e6c7d79c2.webp","/images/venues/b1ea9c403e0b88139c71eaa449a366d8.webp"],
    minGuests: 60, maxGuests: 1000, rooms: 0, outdoor: true, indoor: true, parking: true, catering: true,
    description: "A versatile waterfront space in Pyrmont with stunning views across Darling Harbour. Sydney's go-to venue for large-scale, stylish celebrations.",
    features: ["Darling Harbour Views","Multiple Spaces","In-house Catering","AV & Lighting","Waterfront Access"],
    faqs: [{question:"What is the capacity?",answer:"We can host up to 1,000 guests across all spaces."},{question:"Is there parking?",answer:"Yes, discounted parking is available nearby."}],
    reviews: [{id:1,author:"A Happy Couple",avatar:"A",date:"May 2025",rating:5,text:"Huge space, great views, impeccable food. Loved it!"}],
  },
  {
    id: "venue-istanbul-1",
    name: "Çırağan Palace Kempinski",
    location: "Istanbul Bosphorus",
    city: "Istanbul",
    country: "Global",
    type: "Ottoman Palace",
    price: "₹520000",
    priceUnit: "per day",
    pricePerPlateVeg: "₹10500",
    pricePerPlateNonVeg: "₹16000",
    rentalCost: "₹550000",
    rating: 5.0,
    reviewCount: 387,
    verified: true,
    featured: true,
    image: "/images/venues/b1ea9c403e0b88139c71eaa449a366d8.webp",
    gallery: ["/images/venues/4c6d330355a38b37569cd227bcef593a.webp","/images/venues/9c8c6c14cea93182566c4c5258d97d1d.webp","/images/venues/8728061205a5d7f11820ef4e6c7d79c2.webp"],
    minGuests: 80, maxGuests: 700, rooms: 313, outdoor: true, indoor: true, parking: true, catering: true,
    description: "The last Ottoman imperial palace on the Bosphorus. Marble terraces, frescoed halls, and waterfront gardens create an unmatched historical grandeur.",
    features: ["Bosphorus Views","Ottoman Architecture","In-house Catering","Bridal Suite","Multiple Ballrooms","Water Taxi"],
    faqs: [{question:"Can guests arrive by boat?",answer:"Yes, we have a private dock for water arrivals."},{question:"Is the palace exclusive?",answer:"Full exclusive hire of the palace is available."}],
    reviews: [{id:1,author:"A Happy Couple",avatar:"A",date:"June 2025",rating:5,text:"The most majestic venue we could have imagined — pure history."}],
  },
  {
    id: "venue-istanbul-2",
    name: "Soho House Istanbul",
    location: "Istanbul Beyoğlu",
    city: "Istanbul",
    country: "Global",
    type: "Members Club",
    price: "₹280000",
    priceUnit: "per day",
    pricePerPlateVeg: "₹6000",
    pricePerPlateNonVeg: "₹9200",
    rentalCost: "₹300000",
    rating: 4.6,
    reviewCount: 156,
    verified: true,
    featured: false,
    image: "/images/venues/b1ea9c403e0b88139c71eaa449a366d8.webp",
    gallery: ["/images/venues/9c8c6c14cea93182566c4c5258d97d1d.webp","/images/venues/4c6d330355a38b37569cd227bcef593a.webp","/images/venues/8728061205a5d7f11820ef4e6c7d79c2.webp"],
    minGuests: 30, maxGuests: 250, rooms: 90, outdoor: true, indoor: true, parking: false, catering: true,
    description: "A beautifully restored 19th-century apartment building in the heart of Beyoğlu. Rooftop pool views of the Bosphorus for a modern, stylish celebration.",
    features: ["Rooftop Pool","Bosphorus Views","In-house Catering","Boutique Hotel Rooms","Stylish Décor"],
    faqs: [{question:"Is this a members-only venue?",answer:"No, the venue is available to hire for private events."},{question:"What is the rooftop capacity?",answer:"The rooftop terrace holds up to 120 guests comfortably."}],
    reviews: [{id:1,author:"A Happy Couple",avatar:"A",date:"April 2025",rating:5,text:"Cool, stylish, and utterly beautiful — a perfect wedding!"}],
  },
  {
    id: "venue-istanbul-3",
    name: "Four Seasons Bosphorus",
    location: "Istanbul Beşiktaş",
    city: "Istanbul",
    country: "Global",
    type: "Waterfront Hotel",
    price: "₹410000",
    priceUnit: "per day",
    pricePerPlateVeg: "₹9000",
    pricePerPlateNonVeg: "₹14500",
    rentalCost: "₹440000",
    rating: 4.9,
    reviewCount: 276,
    verified: true,
    featured: false,
    image: "/images/venues/9c8c6c14cea93182566c4c5258d97d1d.webp",
    gallery: ["/images/venues/4c6d330355a38b37569cd227bcef593a.webp","/images/venues/b1ea9c403e0b88139c71eaa449a366d8.webp","/images/venues/8728061205a5d7f11820ef4e6c7d79c2.webp"],
    minGuests: 50, maxGuests: 500, rooms: 170, outdoor: true, indoor: true, parking: true, catering: true,
    description: "A stunning 19th-century Ottoman mansion on the Bosphorus shores, converted into Istanbul's most luxurious waterfront wedding hotel.",
    features: ["Bosphorus Views","Ottoman Architecture","Bridal Suite","In-house Catering","Garden Terrace","Water Access"],
    faqs: [{question:"Is there a garden ceremony option?",answer:"Yes, our gardens slope down to the Bosphorus."},{question:"Can guests stay at the hotel?",answer:"Yes, room blocks are available for wedding guests."}],
    reviews: [{id:1,author:"A Happy Couple",avatar:"A",date:"May 2025",rating:5,text:"Europe meets Asia — the Bosphorus backdrop was unforgettable."}],
  },
];

// ── Seed logic ───────────────────────────────────────────────────────────────
async function seed() {
  console.log("🔗 Connecting to MongoDB...");
  await mongoose.connect(MONGODB_URI, { bufferCommands: false });
  console.log("✅ Connected.");

  const VenueModel = mongoose.models.Venue ?? mongoose.model("Venue", VenueSchema);

  let inserted = 0;
  let updated = 0;

  for (const venue of venues) {
    const doc = {
      venueId:             venue.id,
      name:                venue.name,
      location:            venue.location,
      city:                venue.city,
      country:             venue.country,
      type:                venue.type,
      price:               venue.price,
      priceUnit:           venue.priceUnit,
      pricePerPlateVeg:    venue.pricePerPlateVeg,
      pricePerPlateNonVeg: venue.pricePerPlateNonVeg,
      rentalCost:          venue.rentalCost,
      rating:              venue.rating,
      reviewCount:         venue.reviewCount,
      verified:            venue.verified,
      featured:            venue.featured,
      image:               venue.image,
      gallery:             venue.gallery,
      minGuests:           venue.minGuests,
      maxGuests:           venue.maxGuests,
      rooms:               venue.rooms,
      outdoor:             venue.outdoor,
      indoor:              venue.indoor,
      parking:             venue.parking,
      catering:            venue.catering,
      description:         venue.description,
      features:            venue.features,
      faqs:                venue.faqs,
      reviews:             venue.reviews,
      active:              true,
    };

    const result = await VenueModel.updateOne(
      { venueId: venue.id },
      { $set: doc },
      { upsert: true }
    );

    if (result.upsertedCount > 0) {
      inserted++;
      console.log(`  ➕ Inserted: ${venue.name}`);
    } else {
      updated++;
      console.log(`  🔄 Updated: ${venue.name}`);
    }
  }

  console.log(`\n✅ Done. ${inserted} inserted, ${updated} updated.`);
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error("❌ Seed failed:", err.message);
  process.exit(1);
});
